### ISSUE TITLE
Cannot run sonar on mono-repo lib, tsquery_1.ast error

### ISSUE THREAD

**Issue by devzom** [koliveira15/nx-sonarqube#125]
### Which area/package is the issue in?

@koliveira15/nx-sonarqube

### Description

- **Next.js monorepo on NX@19.14**
- **version: `^4.2.1`**

Trying to configure this lib in a monorepo apps + libs.
Took an 1st try on `i18n` lib. Configured everything based on docs.
Trying local first so:

1. used `npx nx g @koliveira15/nx-sonarqube:config i18n`
2. ran test with coverage
3. then trying to run `npx nx sonar i18n` , it runs successfully tests
but then getting an error:

seems like all config are correct.

What can be the issue or a fix?

```bash
The SonarQube scan failed for project 'i18n'
TypeError: (0 , tsquery_1.ast) is not a function
    at /Users/user/dev/projectx/node_modules/@koliveira15/nx-sonarqube/src/executors/scan/utils/utils.js:106:57
    at Array.forEach (<anonymous>)
    at /Users/user/dev/projectx/node_modules/@koliveira15/nx-sonarqube/src/executors/scan/utils/utils.js:83:14
    at Generator.next (<anonymous>)
    at fulfilled (/Users/user/dev/projectx/node_modules/tslib/tslib.js:167:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

when trying to downgrade the package to "4.1.1" then getting another one

```bash
resolved package json from libs/i18n, package version:0.9.0
The SonarQube scan failed for project 'i18n'
TypeError: sonarQubeScanner.async is not a function
    at /Users/user/dev/projectx/node_modules/@koliveira15/nx-sonarqube/src/executors/scan/utils/utils.js:154:48
    at Generator.next (<anonymous>)
    at fulfilled (/Users/user/dev/projectx/node_modules/tslib/tslib.js:167:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

**Comment by mkalpha** [comment]
Also experiencing this issue. You can get it to work by downgrading the package to 4.1.1, and installing the package sonarqube-scanner and pinning it's version to 3.1.0

**Comment by devzom** [comment]
that's nice @mkalpha  thanks ! tried it right away and **works**!

**Comment by bisfrim** [comment]
@mkalpha i tried doing the same, but getting permission issues 

Unable to open file apps/web/package.json
resolved package json from , package version:0.0.0
[09:05:49] Starting analysis...
[09:05:49] Executable parameters built:
[09:05:49] {
  httpOptions: {},
  targetOS: 'macosx',
  installFolder: '/Users/<username>/.sonar/native-sonar-scanner',
  platformExecutable: '/Users/<username>/.sonar/native-sonar-scanner/sonar-scanner-5.0.1.3006-macosx/bin/sonar-scanner',
  fileName: 'sonar-scanner-cli-5.0.1.3006-macosx.zip',
  downloadUrl: 'https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-macosx.zip'
}
[09:05:49] Trying to find a local install of the SonarScanner: /Users/<username>/.sonar/native-sonar-scanner/sonar-scanner-5.0.1.3006-macosx/bin/sonar-scanner
/bin/sh: /Users/<username>/.sonar/native-sonar-scanner/sonar-scanner-5.0.1.3006-macosx/bin/sonar-scanner: **Permission denied**
[09:05:49] Proceed with download of the platform binaries for SonarScanner...
[09:05:49] Creating /Users/<username>/.sonar/native-sonar-scanner
[====================] 100% 0.0s
[09:05:50] decompressing /Users/<username>/.sonar/native-sonar-scanner/sonar-scanner-cli-5.0.1.3006-macosx.zip into /Users/<username>/.sonar/native-sonar-scanner
[09:05:52] decompressed /Users/<username>/.sonar/native-sonar-scanner/sonar-scanner-5.0.1.3006-macosx/bin/sonar-scanner
[09:05:52] Retrieving info from "package.json" file
The SonarQube scan failed for project 'web'
Error: spawnSync /Users/<username>/.sonar/native-sonar-scanner/sonar-scanner-5.0.1.3006-macosx/bin/sonar-scanner EACCES
    at Object.spawnSync (node:internal/child_process:1124:20)
    at spawnSync (node:child_process:877:24)
    at execFileSync (node:child_process:920:15)
    at scan (/Users/<username>/Documents/adusa/adusa-associatemobility-apps/node_modules/.pnpm/sonarqube-scanner@3.1.0/node_modules/sonarqube-scanner/src/index.js:43:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports.async (/Users/<username>/Documents/adusa/adusa-associatemobility-apps/node_modules/.pnpm/sonarqube-scanner@3.1.0/node_modules/sonarqube-scanner/src/index.js:63:3)

**Comment by devzom** [comment]
@bisfrim tried to cleanup whole workspace and node_modules with reinstall?

**Comment by flo-sch** [comment]
Ran into this issue because `@phenomnomnominal/tsquery` (peerDependency of this package) comes by default in version 5 from `@nx/vite`.

Adding v6 as a direct devDependency fixed the issue.
See: https://github.com/koliveira15/nx-sonarqube/issues/122
